### ISSUE TITLE
Should not add height and overflow styles to container if elementIsScrollable is false

### ISSUE THREAD

**Issue by jinixx** [RealScout/redux-infinite-scroll#50]
If elementIsScrollable is false, the following shouldn't be added to the container, as scroll bar should be on the window itself, not container.

`height: 100%; overflow: scroll;`

**Comment by oscmedgon** [comment]
@jinixx Thats true I fixed this way I hope this hep you.
I added a simple class via classname to avoid overfllow.
I add this class name when the component receives the prop elementIsScrollable to false
`
className={this.props.className + ' ' + !elementIsScrollable && 'disable-scroll'}
`
And this scss code to remove the overflow

``` scss
.redux-infinite-scroll  {
    &.disable-scroll {
        overflow: hidden !important;
    }
}
```
